/**
 * @file ble_att_internal.h
 * @author Surya Poudel
 * @brief Internal ATT protocol definitions for nRF BLE stack
 * @version 0.1
 * @date 2026-05-01
 *
 * @copyright Copyright (c) 2026
 *
 */

#ifndef BLE_ATT_INTERNAL_H__
#define BLE_ATT_INTERNAL_H__

#include "ble_att.h"

#define BLE_ATT_ERR_INVALID_HANDLE 0x01U
#define BLE_ATT_ERR_READ_NOT_PERMITTED 0x02U
#define BLE_ATT_ERR_WRITE_NOT_PERMITTED 0x03U
#define BLE_ATT_ERR_INVALID_PDU 0x04U
#define BLE_ATT_ERR_REQUEST_NOT_SUPPORTED 0x06U
#define BLE_ATT_ERR_ATTRIBUTE_NOT_FOUND 0x0AU
#define BLE_ATT_ERR_INVALID_ATTRIBUTE_VALUE_LEN 0x0DU
#define BLE_ATT_ERR_UNSUPPORTED_GROUP_TYPE 0x10U
#define BLE_ATT_ERR_VALUE_NOT_ALLOWED 0x13U

#define BLE_ATT_OP_ERROR_RESPONSE 0x01U
#define BLE_ATT_OP_EXCHANGE_MTU_REQUEST 0x02U
#define BLE_ATT_OP_EXCHANGE_MTU_RESPONSE 0x03U
#define BLE_ATT_OP_FIND_INFORMATION_REQUEST 0x04U
#define BLE_ATT_OP_FIND_INFORMATION_RESPONSE 0x05U
#define BLE_ATT_OP_FIND_BY_TYPE_VALUE_REQUEST 0x06U
#define BLE_ATT_OP_FIND_BY_TYPE_VALUE_RESPONSE 0x07U
#define BLE_ATT_OP_READ_BY_TYPE_REQUEST 0x08U
#define BLE_ATT_OP_READ_BY_TYPE_RESPONSE 0x09U
#define BLE_ATT_OP_READ_REQUEST 0x0AU
#define BLE_ATT_OP_READ_RESPONSE 0x0BU
#define BLE_ATT_OP_READ_BY_GROUP_TYPE_REQUEST 0x10U
#define BLE_ATT_OP_READ_BY_GROUP_TYPE_RESPONSE 0x11U
#define BLE_ATT_OP_WRITE_REQUEST 0x12U
#define BLE_ATT_OP_WRITE_RESPONSE 0x13U
#define BLE_ATT_OP_HANDLE_VALUE_NOTIFICATION 0x1BU
#define BLE_ATT_OP_HANDLE_VALUE_INDICATION 0x1DU
#define BLE_ATT_OP_HANDLE_VALUE_CONFIRMATION 0x1EU
#define BLE_ATT_OP_WRITE_COMMAND 0x52U

#endif /* BLE_ATT_INTERNAL_H__ */
